version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/var/www
#      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - php-fpm

  mysql:
    image: mysql:5.7
    container_name: db
    command: mysqld --sql_mode=""
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_task
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3308:3306

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  php-fpm:
    image: westside072/php-fpm:7.4.12
    volumes:
      - ./:/var/www/
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    working_dir: /var/www/
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mysql
      - redis

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql